version: "3"

services:
  db:
    image: mysql
    container_name: drink_shop_database
    volumes:
      - ./db/data/mysql:/var/lib/mysql
    env_file:
      - ./db/.env
    ports:
      - 3306
   

  phpmyadmin:
    image: phpmyadmin
    container_name: drink_shop_phpmyadmin
    links:
      - "db"
    environment:
      - PMA_HOST=db
    ports:
      - 8080:80
   

