version: "3"

services:
  db:
    image: mysql
    container_name: drink_shop_database
    volumes:
      - ./db/:/docker-entrypoint-initdb.d
      - ./db/mysql:/var/lib/mysql
    env_file:
      - ./db/.env
    ports:
      - 3306:3306